"""Assembly drawing SVG exporter.

Generates a visual assembly drawing as SVG showing component placement,
reference designators, and board outline. Useful for manufacturing review
and hand-assembly reference.
"""

from __future__ import annotations

import math
from pathlib import Path

from ..core.board import Board
from ..core.component import Component
from ..core.datatypes import Layer, PadShape, Point


class AssemblyDrawingExporter:
    """Generate assembly drawing as SVG."""

    def __init__(self, board: Board, scale: float = 4.0) -> None:
        self.board = board
        self.scale = scale  # pixels per mm

    def export(self, output_path: str | Path) -> str:
        """Export assembly drawing as SVG file. Returns file path."""
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        board = self.board
        s = self.scale
        margin = 15  # px
        w = board.settings.width * s + 2 * margin
        h = board.settings.height * s + 2 * margin + 40  # extra for title

        lines = [
            f'<svg xmlns="http://www.w3.org/2000/svg" width="{w:.0f}" height="{h:.0f}" '
            f'viewBox="0 0 {w:.0f} {h:.0f}">',
            '<style>',
            '  .board-outline { fill: #f5f5dc; stroke: #333; stroke-width: 1.5; }',
            '  .component { fill: none; stroke: #2266cc; stroke-width: 0.8; }',
            '  .pad-smd { fill: #cc4444; opacity: 0.6; }',
            '  .pad-tht { fill: #44cc44; opacity: 0.6; }',
            '  .trace { stroke: #cc8844; stroke-width: 0.5; fill: none; }',
            '  .ref-text { font-family: monospace; font-size: 8px; fill: #333; text-anchor: middle; }',
            '  .title-text { font-family: sans-serif; font-size: 12px; fill: #333; }',
            '  .zone { fill: #88cc88; opacity: 0.15; }',
            '</style>',
        ]

        ox, oy = margin, margin  # origin offset

        # Board outline
        bw = board.settings.width * s
        bh = board.settings.height * s
        lines.append(f'<rect x="{ox}" y="{oy}" width="{bw:.1f}" height="{bh:.1f}" class="board-outline"/>')

        # Copper zones (background)
        for zone in board.zones:
            if zone.outline and len(zone.outline) >= 3:
                pts = " ".join(f"{ox + p.x * s:.1f},{oy + p.y * s:.1f}" for p in zone.outline)
                lines.append(f'<polygon points="{pts}" class="zone"/>')

        # Traces
        for seg in board.get_all_segments():
            x1 = ox + seg.start.x * s
            y1 = oy + seg.start.y * s
            x2 = ox + seg.end.x * s
            y2 = oy + seg.end.y * s
            lines.append(f'<line x1="{x1:.1f}" y1="{y1:.1f}" x2="{x2:.1f}" y2="{y2:.1f}" class="trace"/>')

        # Vias
        for via in board.get_all_vias():
            cx = ox + via.position.x * s
            cy = oy + via.position.y * s
            r = via.diameter / 2 * s
            lines.append(f'<circle cx="{cx:.1f}" cy="{cy:.1f}" r="{r:.1f}" fill="#666" opacity="0.5"/>')

        # Components
        for comp in board.components:
            cx = ox + comp.position.x * s
            cy = oy + comp.position.y * s

            # Courtyard outline
            if comp.footprint.courtyard:
                r = comp.footprint.courtyard.rect
                rx = cx + r.x * s
                ry = cy + r.y * s
                rw = r.width * s
                rh = r.height * s
                lines.append(f'<rect x="{rx:.1f}" y="{ry:.1f}" width="{rw:.1f}" height="{rh:.1f}" class="component"/>')

            # Pads
            for pad in comp.footprint.pads:
                abs_pos = pad.absolute_position(comp.position, comp.rotation)
                px = ox + abs_pos.x * s
                py = oy + abs_pos.y * s
                pw = pad.size_x * s
                ph = pad.size_y * s
                cls = "pad-smd" if pad.is_smd else "pad-tht"

                if pad.shape == PadShape.CIRCLE:
                    lines.append(f'<circle cx="{px:.1f}" cy="{py:.1f}" r="{pw/2:.1f}" class="{cls}"/>')
                else:
                    lines.append(f'<rect x="{px - pw/2:.1f}" y="{py - ph/2:.1f}" width="{pw:.1f}" height="{ph:.1f}" class="{cls}"/>')

            # Reference designator
            lines.append(f'<text x="{cx:.1f}" y="{cy:.1f}" class="ref-text">{comp.reference}</text>')

        # Title block
        ty = oy + bh + 25
        lines.append(f'<text x="{ox}" y="{ty:.0f}" class="title-text" font-weight="bold">{board.name}</text>')
        lines.append(f'<text x="{ox}" y="{ty + 16:.0f}" class="title-text">'
                     f'{board.settings.width:.1f} x {board.settings.height:.1f} mm | '
                     f'{len(board.components)} components | '
                     f'{len(board.nets)} nets | '
                     f'Generated by AI-PCB-Designer</text>')

        lines.append('</svg>')

        output_path.write_text("\n".join(lines))
        return str(output_path)
