"""Microcontrollers and application processors."""

MCUS = [
    # ── ARM Cortex-M (microcontrollers) ────────────────────────────────
    {"mpn": "STM32F103C8T6", "description": "ARM Cortex-M3 72MHz 64KB Flash",
     "package": "LQFP-48", "pins": 48, "category": "arm_cortex_m",
     "key_specs": {"core": "Cortex-M3", "freq_mhz": 72, "flash_kb": 64,
                   "ram_kb": 20, "vdd": "2.0-3.6V", "gpio": 37}},
    {"mpn": "STM32F401CCU6", "description": "ARM Cortex-M4 84MHz 256KB Flash USB",
     "package": "LQFP-48", "pins": 48, "category": "arm_cortex_m",
     "key_specs": {"core": "Cortex-M4F", "freq_mhz": 84, "flash_kb": 256,
                   "ram_kb": 64, "vdd": "1.7-3.6V", "usb": True}},
    {"mpn": "STM32F407VGT6", "description": "ARM Cortex-M4 168MHz 1MB Flash Ethernet",
     "package": "LQFP-100", "pins": 100, "category": "arm_cortex_m",
     "key_specs": {"core": "Cortex-M4F", "freq_mhz": 168, "flash_kb": 1024,
                   "ram_kb": 192, "vdd": "1.8-3.6V", "ethernet": True}},
    {"mpn": "STM32H743VIT6", "description": "ARM Cortex-M7 480MHz 2MB Flash",
     "package": "LQFP-100", "pins": 100, "category": "arm_cortex_m",
     "key_specs": {"core": "Cortex-M7", "freq_mhz": 480, "flash_kb": 2048,
                   "ram_kb": 1024, "vdd": "1.62-3.6V", "usb": True}},
    {"mpn": "STM32L476RGT6", "description": "ARM Cortex-M4 80MHz ultra-low-power",
     "package": "LQFP-64", "pins": 64, "category": "arm_cortex_m",
     "key_specs": {"core": "Cortex-M4F", "freq_mhz": 80, "flash_kb": 1024,
                   "ram_kb": 128, "vdd": "1.71-3.6V", "low_power": True}},
    {"mpn": "STM32G431CBU6", "description": "ARM Cortex-M4 170MHz motor control",
     "package": "QFN-48", "pins": 48, "category": "arm_cortex_m",
     "key_specs": {"core": "Cortex-M4F", "freq_mhz": 170, "flash_kb": 128,
                   "adc_bits": 12, "dac": True}},
    {"mpn": "NRF52840-QIAA-R", "description": "ARM Cortex-M4F BLE 5.0 USB",
     "package": "QFN-48", "pins": 48, "category": "arm_cortex_m",
     "key_specs": {"core": "Cortex-M4F", "freq_mhz": 64, "flash_kb": 1024,
                   "ble": "5.0", "usb": True, "vdd": "1.7-5.5V"}},
    {"mpn": "RP2040", "description": "Dual ARM Cortex-M0+ 133MHz",
     "package": "QFN-56", "pins": 56, "category": "arm_cortex_m",
     "key_specs": {"core": "Dual Cortex-M0+", "freq_mhz": 133,
                   "flash_kb": 0, "ram_kb": 264, "pio": 8, "usb": True}},
    {"mpn": "ATSAMD21G18A-MU", "description": "ARM Cortex-M0+ 48MHz USB",
     "package": "QFN-48", "pins": 48, "category": "arm_cortex_m",
     "key_specs": {"core": "Cortex-M0+", "freq_mhz": 48, "flash_kb": 256,
                   "usb": True}},

    # ── ARM Cortex-A (application processors) ──────────────────────────
    {"mpn": "STM32MP157AAC3", "description": "Dual Cortex-A7 + M4 650MHz DDR3",
     "package": "BGA-196", "pins": 196, "category": "arm_cortex_a",
     "key_specs": {"core": "2xCortex-A7 + Cortex-M4", "freq_mhz": 650,
                   "ddr": "DDR3/DDR3L", "gpu": "3D GPU", "vdd_core": "1.2V",
                   "vdd_io": "1.8V/3.3V", "ethernet": True, "usb": True}},
    {"mpn": "STM32MP153AAC3", "description": "Dual Cortex-A7 + M4 no GPU",
     "package": "BGA-196", "pins": 196, "category": "arm_cortex_a",
     "key_specs": {"core": "2xCortex-A7 + Cortex-M4", "freq_mhz": 650,
                   "ddr": "DDR3/DDR3L"}},
    {"mpn": "MCIMX6Y2CVM05AB", "description": "i.MX6ULL Cortex-A7 528MHz",
     "package": "BGA-289", "pins": 289, "category": "arm_cortex_a",
     "key_specs": {"core": "Cortex-A7", "freq_mhz": 528,
                   "ddr": "DDR3/DDR3L/LPDDR2", "ethernet": True}},
    {"mpn": "ALLWINNER-H3", "description": "Quad Cortex-A7 1.2GHz Mali400",
     "package": "BGA-256", "pins": 256, "category": "arm_cortex_a",
     "key_specs": {"core": "4xCortex-A7", "freq_mhz": 1200,
                   "ddr": "DDR3/DDR3L", "gpu": "Mali-400MP2",
                   "hdmi": True, "ethernet": True}},
    {"mpn": "RK3328", "description": "Quad Cortex-A53 1.5GHz Mali450",
     "package": "BGA-256", "pins": 256, "category": "arm_cortex_a",
     "key_specs": {"core": "4xCortex-A53", "freq_mhz": 1500,
                   "ddr": "DDR3/DDR4/LPDDR3", "gpu": "Mali-450MP2",
                   "usb3": True}},

    # ── ESP32 family ───────────────────────────────────────────────────
    {"mpn": "ESP32-WROOM-32E", "description": "WiFi+BLE MCU module 4MB Flash",
     "package": "ESP32-WROOM-32", "pins": 39, "category": "esp32",
     "key_specs": {"core": "Dual Xtensa LX6", "freq_mhz": 240,
                   "wifi": "802.11b/g/n", "ble": "4.2",
                   "flash_kb": 4096, "vdd": "3.0-3.6V"}},
    {"mpn": "ESP32-S3-WROOM-1", "description": "WiFi+BLE5 AI MCU 8MB Flash",
     "package": "ESP32-WROOM-32", "pins": 39, "category": "esp32",
     "key_specs": {"core": "Dual Xtensa LX7", "freq_mhz": 240,
                   "wifi": "802.11b/g/n", "ble": "5.0",
                   "flash_kb": 8192, "usb": True}},
    {"mpn": "ESP32-C3-MINI-1", "description": "WiFi+BLE5 RISC-V 4MB Flash",
     "package": "QFN-32", "pins": 32, "category": "esp32",
     "key_specs": {"core": "RISC-V", "freq_mhz": 160,
                   "wifi": "802.11b/g/n", "ble": "5.0"}},

    # ── AVR ────────────────────────────────────────────────────────────
    {"mpn": "ATMEGA328P-AU", "description": "AVR 8-bit 20MHz 32KB Flash",
     "package": "TQFP-32", "pins": 32, "category": "avr",
     "key_specs": {"core": "AVR 8-bit", "freq_mhz": 20, "flash_kb": 32,
                   "adc_channels": 8, "vdd": "1.8-5.5V"}},
    {"mpn": "ATTINY85-20SU", "description": "AVR 8-bit 20MHz 8KB Flash",
     "package": "SOIC-8", "pins": 8, "category": "avr",
     "key_specs": {"core": "AVR 8-bit", "freq_mhz": 20, "flash_kb": 8,
                   "gpio": 6}},
]
