"""Motor drivers, relays, and actuator control components."""

MOTOR_RELAY = [
    # ── Motor Driver ICs ───────────────────────────────────────────────
    {"mpn": "DRV8833PWPR", "description": "Dual H-bridge 1.5A motor driver TSSOP-16",
     "package": "TSSOP-16", "pins": 16, "category": "motor_driver",
     "key_specs": {"channels": 2, "iout_a": 1.5, "vin_max": 10.8,
                   "h_bridge": True, "pwm": True}},
    {"mpn": "TB6612FNG", "description": "Dual H-bridge 1.2A SSOP-24",
     "package": "SOIC-24", "pins": 24, "category": "motor_driver",
     "key_specs": {"channels": 2, "iout_a": 1.2, "vin_max": 15,
                   "logic_level": "2.7-5.5V"}},
    {"mpn": "A4988SETTR-T", "description": "Stepper motor driver 2A QFN-28",
     "package": "QFN-28", "pins": 28, "category": "stepper_driver",
     "key_specs": {"iout_a": 2.0, "vin_max": 35, "microstep": "1/16",
                   "use": "NEMA17 stepper motors"}},
    {"mpn": "TMC2209-LA", "description": "Stepper driver StealthChop QFN-28",
     "package": "QFN-28", "pins": 28, "category": "stepper_driver",
     "key_specs": {"iout_a": 2.0, "vin_max": 29, "microstep": "1/256",
                   "uart_config": True, "stealthchop": True}},
    {"mpn": "L298N", "description": "Dual full-bridge 2A DIP-15 / PowerSO-20",
     "package": "DIP-16", "pins": 15, "category": "motor_driver",
     "key_specs": {"channels": 2, "iout_a": 2.0, "vin_max": 46}},
    {"mpn": "L9110S", "description": "Dual H-bridge 800mA SOIC-8",
     "package": "SOIC-8", "pins": 8, "category": "motor_driver",
     "key_specs": {"channels": 2, "iout_ma": 800, "vin_max": 12}},

    # ── Relay Modules ──────────────────────────────────────────────────
    {"mpn": "SRD-05VDC-SL-C", "description": "5V SPDT relay 10A",
     "package": "Relay_SPDT", "pins": 5, "category": "relay",
     "key_specs": {"coil_v": 5, "contact_a": 10, "contact_v": 250,
                   "type": "SPDT",
                   "pinout": "1=Coil+ 2=Coil- 3=COM 4=NO 5=NC",
                   "needs": "NPN transistor + flyback diode"}},
    {"mpn": "SRD-12VDC-SL-C", "description": "12V SPDT relay 10A",
     "package": "Relay_SPDT", "pins": 5, "category": "relay",
     "key_specs": {"coil_v": 12, "contact_a": 10, "type": "SPDT"}},
    {"mpn": "HF46F-5-HS1", "description": "5V SPST-NO relay 5A miniature",
     "package": "Relay_SPDT", "pins": 4, "category": "relay",
     "key_specs": {"coil_v": 5, "contact_a": 5, "type": "SPST-NO"}},

    # ── Transistor Drivers (for relays/solenoids) ──────────────────────
    {"mpn": "ULN2003ADR", "description": "7-ch Darlington driver array SOIC-16",
     "package": "SOIC-16", "pins": 16, "category": "darlington_array",
     "key_specs": {"channels": 7, "iout_ma": 500, "vin_max": 50,
                   "flyback_diodes": "built-in",
                   "use": "drive relays, solenoids, stepper motors"}},
    {"mpn": "2N2222A", "description": "NPN transistor 800mA SOT-23",
     "package": "SOT-23", "pins": 3, "category": "npn",
     "key_specs": {"type": "NPN", "ic_ma": 800, "hfe_min": 100,
                   "vce_max": 40,
                   "pinout": "1=Base 2=Emitter 3=Collector"}},
    {"mpn": "2N7002", "description": "N-FET 60V 300mA SOT-23",
     "package": "SOT-23", "pins": 3, "category": "mosfet",
     "key_specs": {"type": "N-CH", "vds": 60, "ids_ma": 300,
                   "rds_mohm": 1800, "vgs_th": 1.0}},
]
