"""Power supply components: regulators, converters, supervisors, protection."""

POWER = [
    # ── LDO Regulators ────────────────────────────────────────────────
    {"mpn": "AMS1117-3.3", "description": "3.3V LDO 1A SOT-223",
     "package": "SOT-223", "pins": 3, "category": "ldo",
     "key_specs": {"vout": 3.3, "iout_ma": 1000, "vin_max": 15,
                   "dropout_mv": 1100, "pinout": "1=IN 2=GND 3=OUT"}},
    {"mpn": "AMS1117-1.8", "description": "1.8V LDO 1A SOT-223",
     "package": "SOT-223", "pins": 3, "category": "ldo",
     "key_specs": {"vout": 1.8, "iout_ma": 1000, "vin_max": 15}},
    {"mpn": "TLV70033DBVR", "description": "3.3V LDO 150mA ultra-low-noise SOT-23-5",
     "package": "SOT-23-5", "pins": 5, "category": "ldo",
     "key_specs": {"vout": 3.3, "iout_ma": 150, "vin_max": 5.5,
                   "dropout_mv": 165, "noise_uv": 30,
                   "pinout": "1=IN 2=GND 3=EN 4=NC 5=OUT"}},
    {"mpn": "AP2112K-3.3TRG1", "description": "3.3V LDO 600mA SOT-23-5",
     "package": "SOT-23-5", "pins": 5, "category": "ldo",
     "key_specs": {"vout": 3.3, "iout_ma": 600, "vin_max": 6,
                   "dropout_mv": 250}},
    {"mpn": "MCP1700-3302E/TT", "description": "3.3V LDO 250mA ultra-low-Iq SOT-23",
     "package": "SOT-23", "pins": 3, "category": "ldo",
     "key_specs": {"vout": 3.3, "iout_ma": 250, "iq_ua": 1.6}},
    {"mpn": "SPX3819M5-L-3-3", "description": "3.3V LDO 500mA SOT-23-5",
     "package": "SOT-23-5", "pins": 5, "category": "ldo",
     "key_specs": {"vout": 3.3, "iout_ma": 500, "vin_max": 16}},
    {"mpn": "XC6206P332MR", "description": "3.3V LDO 200mA SOT-23",
     "package": "SOT-23", "pins": 3, "category": "ldo",
     "key_specs": {"vout": 3.3, "iout_ma": 200, "iq_ua": 1.0}},
    {"mpn": "RT9080-33GJ5", "description": "3.3V LDO 600mA TSOT-23-5",
     "package": "SOT-23-5", "pins": 5, "category": "ldo",
     "key_specs": {"vout": 3.3, "iout_ma": 600, "dropout_mv": 300}},

    # ── Buck (Step-Down) Converters ────────────────────────────────────
    {"mpn": "TPS54620RGAT", "description": "6A 17V synchronous buck QFN-24",
     "package": "QFN-24", "pins": 24, "category": "buck",
     "key_specs": {"vin_max": 17, "iout_a": 6, "freq_khz": 480,
                   "vout_adj": True, "sync": True}},
    {"mpn": "TPS62172DSGR", "description": "2A 6V micro buck SOT-23-6",
     "package": "SOT-23-6", "pins": 6, "category": "buck",
     "key_specs": {"vin_max": 6, "iout_a": 2, "vout_adj": True}},
    {"mpn": "MP1584EN-LF-Z", "description": "3A 28V buck SOIC-8",
     "package": "SOIC-8", "pins": 8, "category": "buck",
     "key_specs": {"vin_max": 28, "iout_a": 3, "freq_khz": 1500}},
    {"mpn": "LM2596S-5.0", "description": "5V 3A buck TO-263",
     "package": "TO-263", "pins": 5, "category": "buck",
     "key_specs": {"vout": 5.0, "iout_a": 3, "vin_max": 40}},
    {"mpn": "TPS5430DDAR", "description": "3A 36V buck SOIC-8",
     "package": "SOIC-8", "pins": 8, "category": "buck",
     "key_specs": {"vin_max": 36, "iout_a": 3, "freq_khz": 500}},
    {"mpn": "AP3012KTR-G1", "description": "Boost 1.2A SOT-23-5",
     "package": "SOT-23-5", "pins": 5, "category": "boost",
     "key_specs": {"vin_min": 2.6, "vout_max": 25, "iout_a": 1.2}},

    # ── Supervisors / Reset ICs ────────────────────────────────────────
    {"mpn": "MCP130T-300E/TT", "description": "3.0V reset supervisor SOT-23",
     "package": "SOT-23", "pins": 3, "category": "supervisor",
     "key_specs": {"threshold_v": 3.0, "reset_active": "low",
                   "pinout": "1=RST 2=VDD 3=VSS"}},
    {"mpn": "APX809-29SAG-7", "description": "2.93V reset supervisor SOT-23",
     "package": "SOT-23", "pins": 3, "category": "supervisor",
     "key_specs": {"threshold_v": 2.93, "reset_active": "low"}},
    {"mpn": "MAX809TEUR+T", "description": "Reset supervisor with delay SOT-23",
     "package": "SOT-23", "pins": 3, "category": "supervisor",
     "key_specs": {"threshold_v": 3.08, "delay_ms": 140}},

    # ── Power MOSFET switches ──────────────────────────────────────────
    {"mpn": "AO3400A", "description": "N-FET 30V 5.7A SOT-23",
     "package": "SOT-23", "pins": 3, "category": "mosfet",
     "key_specs": {"type": "N-CH", "vds": 30, "ids_a": 5.7,
                   "rds_mohm": 26, "vgs_th": 1.0}},
    {"mpn": "SI2301CDS-T1-GE3", "description": "P-FET -20V -2.8A SOT-23",
     "package": "SOT-23", "pins": 3, "category": "mosfet",
     "key_specs": {"type": "P-CH", "vds": -20, "ids_a": -2.8,
                   "rds_mohm": 80}},
    {"mpn": "IRLZ44NPBF", "description": "N-FET 55V 47A logic-level TO-220",
     "package": "TO-220", "pins": 3, "category": "mosfet",
     "key_specs": {"type": "N-CH", "vds": 55, "ids_a": 47,
                   "rds_mohm": 22, "vgs_th": 2.0}},

    # ── Protection ─────────────────────────────────────────────────────
    {"mpn": "PESD5V0S2BT", "description": "Dual ESD protection 5V SOD-523",
     "package": "SOT-23", "pins": 3, "category": "esd",
     "key_specs": {"vrwm_v": 5.0, "iec_61000_kv": 15}},
    {"mpn": "SMAJ58CA", "description": "58V TVS bidirectional DO-214AC",
     "package": "SOD-123", "pins": 2, "category": "tvs",
     "key_specs": {"vrwm_v": 58, "vcl_v": 93.6, "ipp_a": 3.3}},
    {"mpn": "SS14", "description": "1A 40V Schottky diode SOD-123",
     "package": "SOD-123", "pins": 2, "category": "schottky",
     "key_specs": {"vr_v": 40, "if_a": 1.0, "vf_v": 0.5}},
    {"mpn": "1N5819W", "description": "1A 40V Schottky diode SOD-123",
     "package": "SOD-123", "pins": 2, "category": "schottky",
     "key_specs": {"vr_v": 40, "if_a": 1.0, "vf_v": 0.6}},
    {"mpn": "BAS16", "description": "75V 200mA fast switching diode SOT-23",
     "package": "SOT-23", "pins": 3, "category": "diode",
     "key_specs": {"vr_v": 75, "if_ma": 200}},
]
